node {
    def app
   
    stage ('Clean workspace') {
        cleanWs()
    }
    
    stage ('Git Checkout') {
      
      git branch: 'master', credentialsId: 'ba3bdf3e-3541-4f49-a5aa-0644baf85d8c', url: 'https://github.com/oxitbilisim/villaApi.git'
      
    }
    
    stage('Remove Existing Image') {
        sh('docker image rmi villaadmin-be || (echo "Image villaadmin-be didn\'t exist so not removed."; exit 0)')
    }
      
    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */
    
        app = docker.build("villaadmin-be", "./Villa/")
    }
   
}
